### ISSUE TITLE
bug(pnpm): vue dependency version mismatch

### ISSUE THREAD

**Issue by Aksoom-Hussain** [Lexpeartha/nuxt-xstate#29]
### Your Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.14.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Packages: +5
+++++
Progress: resolved 595, reused 569, downloaded 5, added 5, done

devDependencies:
+ nuxt-xstate 0.5.1

 WARN  Issues with peer dependencies found
.
└─┬ nuxt-xstate 0.5.1
  ├─┬ @xstate/vue 2.0.0
  │ └── ✕ missing peer vue@^3.0.0
  └─┬ xstate-vue2 0.3.0
    ├── ✕ missing peer vue@^2.7.0
    └── ✕ unmet peer @xstate/fsm@^1.0.0: found 2.0.0
✕ Conflicting peer dependencies:
  vue  

Done in 7.2s

**Comment by Lexpeartha** [comment]
This seems like something that can be solved only on per project basis. I tried by adding this to the module's `package.json` file:
```json
"pnpm": {
    "peerDependencyRules": {
      "allowAny": ["@xstate/vue", "xstate-vue2", "vue"]
    }
  }
  ```
  and still got that warning. I think this is because dependencies `@xstate/vue` and `xstate-vue2` themself require vue as peer dependency, and I have no control over that.
  
If you don't want pnpm to fail on peer dependency issues, add `strict-peer-dependencies=false` to an .npmrc file at the root of your project. Either that, or use something like [npm-install-peers](https://www.npmjs.com/package/npm-install-peers) to help you quickly acquire peer deps
